cross_info_rate: 0.8
cross_proba: 0.5
gen_number: 500
mutation_proba: 0.5
page_col: 6
page_row: 6
pop_size: 100
randomizer: true
select_number: 50
sim_matrix_path: sim_default.json
sim_model: null
similarity_coefficient: 0
